### ISSUE TITLE
Error saat menjalankan perintah "node ace migration:run"

### ISSUE THREAD

**Issue by fachrelmarpaung** [akbaraditamasp/guwa-lite#5]
Error: connect ECONNREFUSED 127.0.0.1:6379
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1195:16) {
  errno: -4078,
  code: 'ECONNREFUSED',
  syscall: 'connect',
  address: '127.0.0.1',
  port: 6379
}

**Comment by ondrong** [comment]
redis nya sudah terinstall dan jalan ?

**Comment by akbaraditamasp** [comment]
> Error: connect ECONNREFUSED 127.0.0.1:6379 at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1195:16) { errno: -4078, code: 'ECONNREFUSED', syscall: 'connect', address: '127.0.0.1', port: 6379 }

Atur dulu konfigurasi redisnya mas
